# Generated by Django 3.0.6 on 2020-05-17 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trashed', models.BooleanField(default=False)),
                ('trashed_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=50, verbose_name='nombre del usuario')),
                ('password', models.CharField(max_length=20, verbose_name='Password')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trashed', models.BooleanField(default=False)),
                ('trashed_at', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=20, verbose_name='Role of the User')),
                ('description', models.CharField(max_length=200, verbose_name='Description of the User role')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trashed', models.BooleanField(default=False)),
                ('trashed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20, verbose_name='State of the User')),
                ('description', models.CharField(max_length=200, verbose_name='Description of the User status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trashed', models.BooleanField(default=False)),
                ('trashed_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50, verbose_name='Name of the person')),
                ('last_name', models.CharField(max_length=50, verbose_name='Lastname of the person')),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('signature', models.TextField()),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Login')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Role')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.UserStatus')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
